"""Add status to Equipment model and update FKs

Revision ID: 02c1d284c57b
Revises: 172dde9dc745
Create Date: 2025-04-11 08:12:06.595745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c1d284c57b'
down_revision = '172dde9dc745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50),
                                  nullable=False,
                                  # This tells the DB what default to use for existing rows
                                  server_default='Operational'))
        batch_op.create_index(batch_op.f('ix_equipment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_type'), ['type'], unique=False)

    with op.batch_alter_table('job_card_part', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_job_card_part', ['job_card_id', 'part_id'])

    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_number', sa.String(length=50), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('store',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_part_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_part_number'), ['part_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_store'), ['store'], unique=False)

    with op.batch_alter_table('stock_transaction', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('usage_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_log_log_date'), ['log_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_log_log_date'))

    with op.batch_alter_table('stock_transaction', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_store'))
        batch_op.drop_index(batch_op.f('ix_part_part_number'))
        batch_op.drop_index(batch_op.f('ix_part_name'))
        batch_op.alter_column('store',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('part_number')

    with op.batch_alter_table('job_card_part', schema=None) as batch_op:
        batch_op.drop_constraint('uq_job_card_part', type_='unique')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_type'))
        batch_op.drop_index(batch_op.f('ix_equipment_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
