"""Add MaintenancePlanEntry table

Revision ID: 172dde9dc745
Revises: 4a01a0e9963b
Create Date: 2025-04-10 10:47:13.824166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172dde9dc745'
down_revision = '4a01a0e9963b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_plan_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('task_description', sa.String(length=255), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('interval_type', sa.String(length=50), nullable=True),
    sa.Column('is_estimate', sa.Boolean(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('plan_year', sa.Integer(), nullable=False),
    sa.Column('plan_month', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name='fk_plan_entry_equipment_id'),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_task.id'], name='fk_plan_entry_task_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_plan_entry', schema=None) as batch_op:
        batch_op.create_index('ix_maintenance_plan_entry_year_month', ['plan_year', 'plan_month'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_plan_entry', schema=None) as batch_op:
        batch_op.drop_index('ix_maintenance_plan_entry_year_month')

    op.drop_table('maintenance_plan_entry')
    # ### end Alembic commands ###
