"""Inital setup

Revision ID: 45e1ea3da58d
Revises: 
Create Date: 2025-04-09 14:46:22.929256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e1ea3da58d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('checklist_required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('contact_info', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('check_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name='fk_checklist_equipment_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_number', sa.String(length=20), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('technician', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('oem_required', sa.Boolean(), nullable=True),
    sa.Column('kit_required', sa.Boolean(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name='fk_job_card_equipment_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_number')
    )
    op.create_table('maintenance_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('interval_type', sa.String(length=50), nullable=False),
    sa.Column('interval_value', sa.Integer(), nullable=False),
    sa.Column('oem_required', sa.Boolean(), nullable=True),
    sa.Column('kit_required', sa.Boolean(), nullable=True),
    sa.Column('last_performed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name='fk_maintenance_task_equipment_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_get', sa.Boolean(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('store', sa.String(length=20), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name='fk_part_supplier_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('usage_value', sa.Float(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name='fk_usage_log_equipment_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_card_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_card.id'], name='fk_job_card_part_job_card_id'),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], name='fk_job_card_part_part_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], name='fk_stock_transaction_part_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_transaction')
    op.drop_table('job_card_part')
    op.drop_table('usage_log')
    op.drop_table('part')
    op.drop_table('maintenance_task')
    op.drop_table('job_card')
    op.drop_table('checklist')
    op.drop_table('supplier')
    op.drop_table('equipment')
    # ### end Alembic commands ###
