"""Add last_performed_usage_value to MaintenanceTask

Revision ID: 4a01a0e9963b
Revises: b16de4c156ec
Create Date: 2025-04-10 09:20:59.744517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a01a0e9963b'
down_revision = 'b16de4c156ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_performed_usage_value', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_task', schema=None) as batch_op:
        batch_op.drop_column('last_performed_usage_value')

    # ### end Alembic commands ###
