"""Add is_legal_compliance to MaintenanceTask

Revision ID: 723332a93ab2
Revises: 02c1d284c57b
Create Date: 2025-04-16 08:28:10.623562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723332a93ab2'
down_revision = '02c1d284c57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_legal_compliance', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_maintenance_task_is_legal_compliance'), ['is_legal_compliance'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_task_is_legal_compliance'))
        batch_op.drop_column('is_legal_compliance')

    # ### end Alembic commands ###
