"""Add due_date to JobCard

Revision ID: b16de4c156ec
Revises: 45e1ea3da58d
Create Date: 2025-04-09 15:24:34.227913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16de4c156ec'
down_revision = '45e1ea3da58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_card', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
